---
- name: Implementing loops
  hosts: all
  tasks:
    - name: Install s/w apps
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - tree
        - openjdk-21-jdk
        - maven
...
